---
- name: Download Hadoop
  hosts: all
  tasks:
      - get_url: 
          url: http://apache.lauf-forum.at/hadoop/common/hadoop-2.9.0/hadoop-2.9.0-src.tar.gz
          dest: ~/

- name: Extract Hadoop
  hosts: all
  tasks:
      - unarchive: 
          src: /home/root/hadoop-2.9.0.tar.gz 
          dest: /usr/local owner=root 
          group: root 
          creates: /usr/local/hadoop 
          copy: no

      - command: mv /usr/local/hadoop-2.9.0 /usr/local/hadoop creates=/usr/local/hadoop removes=/usr/local/hadoop-2.9.0

      - lineinfile: path=/root/.bashrc regexp="HADOOP_PREFIX=" line="export HADOOP_PREFIX=/usr/local/hadoop"
      - lineinfile: path=/root/.bashrc regexp="PATH=" line="export PATH=$PATH:$HADOOP_PREFIX/bin"

- name: Update the xml files
  hosts: all
  tasks:
      - template: src={{ item.src }} dest={{ item.dest }} owner="root" group="root"
        with_items:
         - {src: "core-site.xml", dest: "/usr/local/hadoop/etc/hadoop/core-site.xml"}
         - {src: "hdfs-site.xml", dest: "/usr/local/hadoop/etc/hadoop/hdfs-site.xml"}
         - {src: "yarn-site.xml", dest: "/usr/local/hadoop/etc/hadoop/yarn-site.xml"}
         - {src: "mapred-site.xml", dest: "/usr/local/hadoop/etc/hadoop/yarn-site.xml"}
