---
- name: Configure static hostnames for machines
  hosts: all
  tasks:
    - name: Copy script to assign hostname to ip
      copy:
        src: scripts/assign_ip_to_hostname.sh
        dest: ~/
        owner: root
        mode: +x
    - name: Copy rc.local so that it calls script on startup
      copy:
        src: templates/rc.local
        dest: /etc/
        owner: root
        mode: +x
        
